/**
 * ChannelInvite automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

using System.Text.Json.Serialization;

namespace SdkFabric.Discord;

public class ChannelInvite
{
    [JsonPropertyName("max_age")]
    public int? MaxAge { get; set; }

    [JsonPropertyName("max_uses")]
    public int? MaxUses { get; set; }

    [JsonPropertyName("temporary")]
    public bool? Temporary { get; set; }

    [JsonPropertyName("unique")]
    public bool? Unique { get; set; }

    [JsonPropertyName("target_type")]
    public int? TargetType { get; set; }

    [JsonPropertyName("target_user_id")]
    public string? TargetUserId { get; set; }

    [JsonPropertyName("target_application_id")]
    public string? TargetApplicationId { get; set; }

}

