/**
 * ChannelTag automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */


using System.Collections.Generic;
using System.Text.Json;
using System.Threading.Tasks;
using RestSharp;
using Sdkgen.Client;
using Sdkgen.Client.Exception;

namespace SdkFabric.Discord;

public class ChannelTag : TagAbstract {
    public ChannelTag(RestClient httpClient, Parser parser): base(httpClient, parser)
    {
    }

    public ChannelMessageTag Message()
    {
        return new ChannelMessageTag(
            this.HttpClient,
            this.Parser
        );
    }


}
