/**
 * Client automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */


using System.Collections.Generic;
using System.Text.Json;
using System.Threading.Tasks;
using RestSharp;
using Sdkgen.Client;
using Sdkgen.Client.Credentials;
using Sdkgen.Client.Exception;

namespace SdkFabric.Discord;

public class Client : ClientAbstract
{
    public Client(string baseUrl, ICredentials credentials) : base(baseUrl, credentials)
    {
    }

    public ChannelTag Channel()
    {
        return new ChannelTag(
            this.HttpClient,
            this.Parser
        );
    }



    public static Client Build(string clientId, string clientSecret, ITokenStore tokenStore, List<string> scopes)
    {
        return new Client("https://discord.com/api/v10", new OAuth2(clientId, clientSecret, "https://discord.com/api/oauth2/token", "https://discord.com/oauth2/authorize", tokenStore, scopes));
    }
}
